import type { Metadata } from "next";
import { Inter, Roboto } from "next/font/google";  // Correctly import both Inter and Roboto
import "./globals.css";

// Configure the Roboto font
const roboto = Roboto({
  weight: ['400', '700'],
  subsets: ['latin'],
  display: 'swap',
});

// Configure the Inter font if you need it (uncomment if required)
// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>{children}</body>
    </html>
  );
}
