import { Inter } from 'next/font/google';
import './globals.css';
import { Inter as FontSans } from 'next/font/google';
import { SessionProvider } from '@/accountProvider/sessionProvider';
import { cn } from '@/lib/utils';
import { auth } from '@/auth';
import { NavBar } from '@/components/NavBar';
import { ThemeProvider } from '@/components/ThemeProvider';
import Providers from '@/utils/queryProvider';

const fontSans = FontSans({
  subsets: ['latin'],
  variable: '--font-sans',
});


const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  const session = await auth();
  const user = {
    name: session?.user?.name || 'Guest',
    image: session?.user?.image || '',
    email: session?.user?.email || ''
  };
  return (
    <html lang="en">
      <body className={cn('min-h-screen font-sans antialiased', fontSans.variable)}>
        <SessionProvider>
        <Providers>
         
            <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
              <NavBar user={user} />
              {children}
            </ThemeProvider>
            </Providers>
         
         </SessionProvider>
      </body>
    </html>
  );
}
